#!/usr/bin/env bash
set -euo pipefail

# Setup Next.js App for AppGen
# Usage: ./setup-nextjs-app.sh "project-name" "/output/path"

PROJECT_NAME="${1:?Error: Project name required}"
OUTPUT_DIR="${2:?Error: Output directory required}"
PROJECT_DIR="${OUTPUT_DIR}/${PROJECT_NAME} - appgen"

echo "🚀 Setting up Next.js app: ${PROJECT_NAME}"

# Create project directory
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Initialize Next.js with TypeScript and Tailwind
npx create-next-app@latest . \
  --typescript \
  --tailwind \
  --app \
  --no-src-dir \
  --import-alias "@/*" \
  --use-npm \
  --yes

# Create additional directories
mkdir -p lib components/ui components/features tests/{unit,integration,e2e} docs database api research

# Create tsconfig with strict mode
cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

# Create .env.example
cat > .env.example <<'EOF'
# Database
DATABASE_URL="postgresql://user:password@localhost:5432/dbname"

# Auth
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-secret-here"

# App
NODE_ENV="development"
EOF

# Create README
cat > README.md <<EOF
# ${PROJECT_NAME}

Full-stack Next.js application generated by appgen.

## Tech Stack

- **Framework:** Next.js 15 (App Router)
- **Language:** TypeScript (strict mode)
- **Styling:** Tailwind CSS
- **Database:** PostgreSQL + Prisma (to be configured)
- **Auth:** Auth.js (to be configured)

## Getting Started

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Configure environment:**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your database connection and secrets
   \`\`\`

3. **Set up database:**
   \`\`\`bash
   # After Prisma is configured:
   npm run db:migrate
   npm run db:seed  # If seed script exists
   \`\`\`

4. **Run development server:**
   \`\`\`bash
   npm run dev
   \`\`\`

   Open [http://localhost:3000](http://localhost:3000)

## Project Structure

\`\`\`
${PROJECT_NAME}/
├── app/              # Next.js App Router
├── components/       # React components
├── lib/              # Utilities, database, auth
├── prisma/           # Database schema
├── tests/            # Test files
└── docs/             # Documentation
\`\`\`

## Scripts

- \`npm run dev\` - Start development server
- \`npm run build\` - Build for production
- \`npm run start\` - Start production server
- \`npm run lint\` - Run ESLint
- \`npm test\` - Run tests

## Documentation

- [Architecture](./docs/architecture.md)
- [Database Schema](./database/schema.md)
- [API Design](./api/design.md)

---

🤖 Generated with appgen v1.0
EOF

echo "✅ Next.js app scaffolded at: ${PROJECT_DIR}"
echo "📝 Next steps:"
echo "   1. cd \"${PROJECT_DIR}\""
echo "   2. npm install"
echo "   3. Configure Prisma and Auth"
echo "   4. npm run dev"
