#!/usr/bin/env bash
set -euo pipefail

# Setup Turborepo Monorepo for AppGen
# Usage: ./setup-monorepo.sh "project-name" "/output/path"

PROJECT_NAME="${1:?Error: Project name required}"
OUTPUT_DIR="${2:?Error: Output directory required}"
PROJECT_DIR="${OUTPUT_DIR}/${PROJECT_NAME} - appgen"

echo "🚀 Setting up Turborepo monorepo: ${PROJECT_NAME}"

# Create using Turborepo template
npx create-turbo@latest "$PROJECT_DIR" --package-manager npm

cd "$PROJECT_DIR"

# Create additional directories
mkdir -p docs database api research

# Create .env.example at root
cat > .env.example <<'EOF'
# Database (shared)
DATABASE_URL="postgresql://user:password@localhost:5432/dbname"

# Auth
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-secret-here"
JWT_SECRET="your-jwt-secret-here"

# App-specific
WEB_PORT=3000
API_PORT=3001
EOF

# Update root README
cat > README.md <<EOF
# ${PROJECT_NAME}

Turborepo monorepo with Next.js web app and Hono API, generated by appgen.

## What's Inside?

This monorepo includes:

### Apps

- \`web\`: Next.js 15 (App Router) web application
- \`api\`: Hono API server

### Packages

- \`database\`: Prisma schema and database client (shared)
- \`ui\`: Shared React component library
- \`typescript-config\`: Shared TypeScript configurations
- \`eslint-config\`: Shared ESLint configurations

## Getting Started

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Configure environment:**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your configuration
   \`\`\`

3. **Set up database:**
   \`\`\`bash
   cd packages/database
   npx prisma migrate dev
   \`\`\`

4. **Run all apps:**
   \`\`\`bash
   npm run dev
   \`\`\`

   - Web: [http://localhost:3000](http://localhost:3000)
   - API: [http://localhost:3001](http://localhost:3001)

## Scripts

- \`npm run dev\` - Start all apps in development mode
- \`npm run build\` - Build all apps and packages
- \`npm run lint\` - Lint all apps and packages
- \`npm run test\` - Run tests across all packages

## Turborepo Features

- **Caching:** Tasks are cached for faster builds
- **Remote Caching:** Share cache across team (optional)
- **Parallel Execution:** Run tasks across packages in parallel
- **Dependency Graph:** Only rebuild what changed

## Documentation

- [Architecture](./docs/architecture.md)
- [Database Schema](./database/schema.md)
- [API Design](./api/design.md)

---

🤖 Generated with appgen v1.0
EOF

echo "✅ Turborepo monorepo scaffolded at: ${PROJECT_DIR}"
echo "📝 Next steps:"
echo "   1. cd \"${PROJECT_DIR}\""
echo "   2. npm install"
echo "   3. Set up shared database package"
echo "   4. npm run dev"
