#!/usr/bin/env bash
set -euo pipefail

# Setup API-Only Project for AppGen
# Usage: ./setup-api-only.sh "project-name" "/output/path" "hono|express|fastify"

PROJECT_NAME="${1:?Error: Project name required}"
OUTPUT_DIR="${2:?Error: Output directory required}"
FRAMEWORK="${3:-hono}"  # Default to Hono
PROJECT_DIR="${OUTPUT_DIR}/${PROJECT_NAME} - appgen"

echo "🚀 Setting up ${FRAMEWORK} API: ${PROJECT_NAME}"

# Create project directory
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Initialize package.json
npm init -y

# Install dependencies based on framework
case "$FRAMEWORK" in
  "hono")
    npm install hono @hono/node-server
    ENTRY_FILE="hono-app"
    ;;
  "express")
    npm install express
    npm install -D @types/express
    ENTRY_FILE="express-app"
    ;;
  "fastify")
    npm install fastify
    ENTRY_FILE="fastify-app"
    ;;
  *)
    echo "❌ Unknown framework: $FRAMEWORK"
    echo "Supported: hono, express, fastify"
    exit 1
    ;;
esac

# Install common dependencies
npm install dotenv zod
npm install -D typescript @types/node tsx

# Create directories
mkdir -p src/{routes,services,middleware,types} tests/{unit,integration} docs database api research

# Initialize TypeScript with strict mode
npx tsc --init --strict --skipLibCheck --target ES2022 --module NodeNext --moduleResolution NodeNext --outDir dist

# Update tsconfig.json
cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2022"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
EOF

# Create entry point based on framework
cat > "src/index.ts" <<EOF
import 'dotenv/config';
import { app } from './app';

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(\`🚀 API server running on port \${PORT}\`);
});
EOF

# Create app file based on framework
if [ "$FRAMEWORK" = "hono" ]; then
  cat > "src/app.ts" <<'EOF'
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger } from 'hono/logger';

const app = new Hono();

// Middleware
app.use('*', logger());
app.use('*', cors());

// Health check
app.get('/health', (c) => {
  return c.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// API routes
app.get('/api/v1', (c) => {
  return c.json({ message: 'API v1' });
});

export { app };
EOF
elif [ "$FRAMEWORK" = "express" ]; then
  cat > "src/app.ts" <<'EOF'
import express from 'express';
import cors from 'cors';

const app = express();

// Middleware
app.use(express.json());
app.use(cors());

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// API routes
app.get('/api/v1', (req, res) => {
  res.json({ message: 'API v1' });
});

export { app };
EOF
else  # Fastify
  cat > "src/app.ts" <<'EOF'
import fastify from 'fastify';

const app = fastify({ logger: true });

// Health check
app.get('/health', async (request, reply) => {
  return { status: 'ok', timestamp: new Date().toISOString() };
});

// API routes
app.get('/api/v1', async (request, reply) => {
  return { message: 'API v1' };
});

export { app };
EOF
fi

# Create .env.example
cat > .env.example <<'EOF'
# Server
PORT=3000
NODE_ENV=development

# Database
DATABASE_URL="postgresql://user:password@localhost:5432/dbname"

# Auth
JWT_SECRET="your-jwt-secret-here"
JWT_EXPIRES_IN="7d"

# CORS
ALLOWED_ORIGINS="http://localhost:3000,http://localhost:5173"
EOF

# Create .gitignore
cat > .gitignore <<'EOF'
node_modules/
dist/
.env
.DS_Store
*.log
coverage/
.vscode/
.idea/
EOF

# Update package.json scripts
npm pkg set scripts.dev="tsx watch src/index.ts"
npm pkg set scripts.build="tsc"
npm pkg set scripts.start="node dist/index.js"
npm pkg set scripts.lint="tsc --noEmit"
npm pkg set scripts.test="echo 'Tests to be configured'"

# Create README
cat > README.md <<EOF
# ${PROJECT_NAME}

${FRAMEWORK} API server generated by appgen.

## Tech Stack

- **Framework:** ${FRAMEWORK}
- **Language:** TypeScript (strict mode)
- **Database:** PostgreSQL + Prisma (to be configured)
- **Validation:** Zod
- **Auth:** JWT (to be configured)

## Getting Started

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Configure environment:**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your configuration
   \`\`\`

3. **Set up database:**
   \`\`\`bash
   # After Prisma is configured:
   npm run db:migrate
   \`\`\`

4. **Run development server:**
   \`\`\`bash
   npm run dev
   \`\`\`

   API available at [http://localhost:3000](http://localhost:3000)

## Project Structure

\`\`\`
${PROJECT_NAME}/
├── src/
│   ├── routes/       # API route handlers
│   ├── services/     # Business logic
│   ├── middleware/   # Auth, validation
│   ├── types/        # TypeScript types
│   └── index.ts      # Entry point
├── prisma/           # Database schema
├── tests/            # Test files
└── docs/             # Documentation
\`\`\`

## Scripts

- \`npm run dev\` - Start development server (hot reload)
- \`npm run build\` - Compile TypeScript
- \`npm run start\` - Start production server
- \`npm run lint\` - Type check
- \`npm test\` - Run tests

## API Endpoints

### Health Check
\`\`\`
GET /health
\`\`\`

Returns server status.

## Documentation

- [API Design](./api/design.md)
- [Database Schema](./database/schema.md)

---

🤖 Generated with appgen v1.0
EOF

echo "✅ ${FRAMEWORK} API scaffolded at: ${PROJECT_DIR}"
echo "📝 Next steps:"
echo "   1. cd \"${PROJECT_DIR}\""
echo "   2. npm install"
echo "   3. Configure Prisma and Auth"
echo "   4. npm run dev"
